### ISSUE TITLE
Amazon Flex Bot

### ISSUE THREAD

**Issue by mergim69** [cyleleghorn/AmazonFlexChecker#5]
Hi, 

please contact me . I'm interested on the grab bot. I had one for over one year but the guy who installed me everything is so unreliable, when i have questions or problems ...
Can you create me one please,
attached some pics from my former bot
bye
Mergim

![Screenshot_20210204-085301](https://user-images.githubusercontent.com/78556472/106928330-5e5b1880-6713-11eb-9b28-7ee7c70eb59f.jpg)
![Screenshot_20210204-085316](https://user-images.githubusercontent.com/78556472/106928332-5ef3af00-6713-11eb-81a0-29222441943d.jpg)
![Screenshot_20210204-085323](https://user-images.githubusercontent.com/78556472/106928335-5ef3af00-6713-11eb-8e2f-d450c7dcd6d9.jpg)
![Screenshot_20210204-085335](https://user-images.githubusercontent.com/78556472/106928337-5f8c4580-6713-11eb-8e24-e0ada0e2cc2f.jpg)
![Screenshot_20210204-085402](https://user-images.githubusercontent.com/78556472/106928339-5f8c4580-6713-11eb-841a-81097b283a22.jpg)

**Comment by theramzaan** [comment]
Website name

**Comment by theramzaan** [comment]
Hey there 

We looking for make amazon flex grabber webpage in India if you any can help please suggest the details
